#!/usr/bin/env bash
# Top-level audit runner. Runs every audit script in turn and writes a
# consolidated report to docs/regulations/aadc/AUDIT.md in the target
# project root.
#
# Usage:
#   scripts/audit.sh <target-project-root>
#
# Set audit-specific env vars before invocation if you need to customise
# the allowlists for your project. See individual scripts for details.

set -euo pipefail

# Resolve where the audit scripts live. Two installation shapes:
#   (a) running from the repo itself:  $here = .../aadc-audit-mcp/legacy-bash
#   (b) installed into a target repo:   $here = .../tools/aadc
# In both cases the sibling audit-*.sh scripts are right next to us.
here="$(cd "$(dirname "$0")" && pwd)"
root="${1:-.}"
cd "$root"

mkdir -p docs/regulations/aadc

report="docs/regulations/aadc/AUDIT.md"

{
  echo "# AADC audit (auto-generated)"
  echo ""
  echo "Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo ""
  echo "This file is REGENERATED by \`scripts/audit.sh\`. Edit the audit"
  echo "scripts themselves if a check is wrong; do not hand-edit this file"
  echo "for anything that the scripts could have caught. The per-standard"
  echo "narrative + non-automatable judgement entries belong in the"
  echo "conformance statement, not here."
  echo ""
} > "$report"

run_audit () {
  local name="$1"
  shift
  echo "## $name" >> "$report"
  echo "" >> "$report"
  echo '```' >> "$report"
  if "$@" >> "$report" 2>&1; then
    echo '```' >> "$report"
    echo "" >> "$report"
    echo "Status: PASS" >> "$report"
  else
    echo '```' >> "$report"
    echo "" >> "$report"
    echo "Status: FAIL" >> "$report"
  fi
  echo "" >> "$report"
  echo "---" >> "$report"
  echo "" >> "$report"
}

run_audit "Native permission allowlist (Standards 8, 10)" \
  "$here/audit-permissions.sh" "$root"
run_audit "Third-party SDK allowlist (Standards 5, 9, 12, 13)" \
  "$here/audit-sdks.sh" "$root"
run_audit "Outbound-link mode (Standards 11, 14)" \
  "$here/audit-launchurl.sh" "$root"

if [ -n "${AADC_PROTECTED_PATHS:-}" ]; then
  run_audit "Network isolation in must-not-network paths (Standard 8)" \
    "$here/audit-network-isolation.sh" "$root" "$AADC_PROTECTED_PATHS"
else
  {
    echo "## Network isolation"
    echo ""
    echo "SKIPPED — set AADC_PROTECTED_PATHS to enable this check."
    echo ""
    echo "---"
    echo ""
  } >> "$report"
fi

run_audit "Privacy-positive defaults (Standard 7)" \
  "$here/audit-defaults.sh" "$root"

echo "Report written to $report"
